### ISSUE TITLE
Documentation update for installing on Ubuntu 16.10

### ISSUE THREAD

**Issue by beaugunderson** [IteratorAdvance/taichi#10]
I followed the 16.04 instructions to install on a new Ubuntu 16.10 VM but the library ended up being linked with `-lpython3.5m` and would not work.

To link with python 2.7 I had to use this cmake command:

```
cmake \
  -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7 \
  -DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7 \
  -DPYTHON_LIBRARY:FILEPATH=/usr/lib/x86_64-linux-gnu/libpython2.7.so \
  ..
```

**Comment by IteratorAdvance** [comment]
Another way may be changing the line 
```
find_package(PythonLibs REQUIRED)
```
with 
```
find_package(PythonLibs 2.7 REQUIRED)
```

Different versions of python can be indeed a tricky problem. I hope this solves the coexistence of python 2 and 3.

Things become more complicated with different version python 2, which is the case on my Mac. My situation is like brew installs boost::python with python 2.7.8 and CMake finds python 2.7.10 (the version required by the system) thus results in a mess. I'm looking for a better solution other than hard coding.

**Comment by IteratorAdvance** [comment]
Thanks for the feedback.

I updated the python configuration finder and now the default `python` in bash will be used. You can also specify your own python by simply  add `-DPYTHON_EXECUTABLE:FILEPATH=/usr/bin/python2.7` to cmake options.

You are welcome to have a try.

**Comment by IteratorAdvance** [comment]
I also updated the doc about python issue during installing, but I haven't actually tested it on Ubuntu 16.10.
