### ISSUE TITLE
MacOSX ImportError: No module named taichi

### ISSUE THREAD

**Issue by iamyoukou** [IteratorAdvance/taichi#20]
Hi, I built libtaichi_core.dylib successfully, following the Mac OS X part of Wiki.
But when I run
`$python2.7`
`>>> import taichi as tc `
I got
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named taichi
```
What should I do?

**Comment by IteratorAdvance** [comment]
Hi, please add
```
export PYTHONPATH=$TAICHI_ROOT_DIR/taichi/python/:$PYTHONPATH
```
to your ~/.bashrc.

Thanks.

BTW, did you encountered difficulty during compiling Taichi? (I'm just curious about if my Mac installation guide was written correctly.)

**Comment by iamyoukou** [comment]
Thanks, the `No module named taichi` error is gone. But I got
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/__init__.py", line 1, in <module>
    from taichi.core import tc_core as core
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/core/__init__.py", line 1, in <module>
    from load_core import tc_core
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/core/load_core.py", line 18, in <module>
    import taichi_core as tc_core
ImportError: dlopen(./taichi_core.so, 2): Library not loaded: libboost_system.dylib
  Referenced from: /Users/YJ-work/Desktop/taichi_root/taichi/build/taichi_core.so
  Reason: image not found
```
I'm new to Python, so I don't know how to solve this X_X

**For your Mac installation guide**:
I installed python with MacPorts, and MacPorts has no `boost-python` thing. 
So I downloaded and built `libboost_system.dylib`, `libboost_python.dylib' from [Boost](http://www.boost.org/). 
Then I put these two dylib into directory `$PYTHON_LIBRARIES`. 
Otherwise, the build will fail.

**Comment by IteratorAdvance** [comment]
Hi Jiang,

Thanks for the feedback. This is probably because `libboost_system.dylib` is not found by your linker. Where did you put `libboost_system.dylib` and `libboost_python.dylib`?  On my Mac they are at `/usr/local/lib/`. You can try copy them there. Another option is to put them at `$TAICHI_ROOT_DIR/taichi/build/`.

**Comment by iamyoukou** [comment]
My fault. Since MacPorts always install library in `/opt/local/lib/`, I copy `libboost_system.dylib` and `libboost_python.dylib` into that directory without any thinking : )
After I copy those two dylib into `/usr/local/lib`, the error is gone.
Now the `import taichi as tc` test executed correctly.
Thank you very much!

BTW, for MacPorts users:
1. If you use `python2.7`, please install `py27-numpy`, `py27-future`, `py27-futures`, `p27-watchdog`, `py27-Pillow` and `py27-scipy`, because there're also py26, py34 versions.

2. Of course, `$python2.7` instead of `$python`.

**Comment by IteratorAdvance** [comment]
Great. I guess now you can play with `Taichi` by running the examples.

If you would like to, please write down a little bit about your installation process with MacPorts on OS X, on the `Getting Started` page. It's OK to just make a draft; I'll put them in proper format later.
