### ISSUE TITLE
Issue with building on ubuntu 14.04

### ISSUE THREAD

**Issue by cjbarb7** [IteratorAdvance/taichi#22]
Keep getting this issue when installing it with make -j 2

fatal error: taichi/dynamics/poisson_solver2D.h: No such file or directory
 #include <taichi/dynamics/poisson_solver2D.h>
                                              ^
compilation terminated.
make[2]: *** [CMakeFiles/taichi_core.dir/src/simulation3d/poisson_solver2d.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
make: *** [all] Error 2

**Comment by IteratorAdvance** [comment]
Thanks for the feedback. I've fixed it.
