### ISSUE TITLE
CMakeList 中Boost大小写问题

### ISSUE THREAD

**Issue by zq317157782** [IteratorAdvance/taichi#24]
` include_directories(${BOOST_INCLUDE_DIRS})`     
  中Boost是全大写，但是
`find_package(Boost COMPONENTS
        system
        python REQUIRED)`
中Boost是区分大小写，导致osx下无法寻找到正确的路径

**Comment by IteratorAdvance** [comment]
So you mean it should be `include_directories(${Boost_INCLUDE_DIRS})`?

**Comment by zq317157782** [comment]
${BOOST_INCLUDE_DIRS} is empty in my OSX ,
when i change it to Boost_INCLUDE_DIRS, ${Boost_INCLUDE_DIRS}'s value is right.

**Comment by IteratorAdvance** [comment]
Thanks for letting me know. I guess I fixed this problem in previous commits. Please pull and reconfigure. I think it will work. It's interesting that on my Mac both identifiers work. I changed it to `Boost_INCLUDE_DIRS` last night anyway.
