### ISSUE TITLE
Function name misc.util.get_uuid() is confusing

### ISSUE THREAD

**Issue by yczhang89** [IteratorAdvance/taichi#4]
UUID is a well-known identifier standard with a format like `123e4567-e89b-12d3-a456-426655440000`. This function does not generate UUIDs.

**Comment by IteratorAdvance** [comment]
Sure, you are right. It's definitely a confusing and misleading identifier. I'll fix it soon.

**Comment by IteratorAdvance** [comment]
I marked that as deprecated and we can gradually change to get_unique_task_id instead.
