### ISSUE TITLE
nbody example fails

### ISSUE THREAD

**Issue by bwanaaa** [IteratorAdvance/taichi#5]
~/taichi/taichi/python/examples/simulation$ python nbody_3d.py 

```
[Errno 2] No such file or directory: '../output/frames/task-2017-01-05-20-58-23-r03610/'
Simulation time: 0.0
nbody.cpp[201]: node_end = 297117
Time: 0.139370918274
Segmentation fault (core dumped)
```

I think the error is nbody.py where this line:
`self.directory = '../output/frames/' + get_uuid() + '/'`

Maybe should be:
`self.directory = tc.get_root_directory() + 'output/frames/' + get_uuid() + '/'`

added this:
`import taichi as tc`

but then get this error:
```
python nbody_3d.py 
[Errno 2] No such file or directory: '/home/me/taichi/output/frames/task-2017-01-05-21-19-15-r07527/'
Simulation time: 0.0
nbody.cpp[201]: node_end = 297117
Time: 0.115436077118
Segmentation fault (core dumped)
```
as if it cannot os.mkdir(self.directory)

**Comment by IteratorAdvance** [comment]
Thanks for pointing this out. I fixed the directory issue and it runs well on my machine. Could you please have a try?

**Comment by iamyoukou** [comment]
I had the same error on Arch Linux. And I  
`mkdir $TAICHI_ROOT_DIR/taichi_outputs`
as @IteratorAdvance you pointed out in another issue, and problem solved.

**Comment by IteratorAdvance** [comment]
OK, thanks. I'll put a script at startup so that users do not have to manually `mkdir`.
