### ISSUE TITLE
go language binding / port 

### ISSUE THREAD

**Issue by acterhd** [IteratorAdvance/taichi#6]
Hello. Will support this iterator for go language? I also have own path tracing, but for different purpose, so have no much functions. I know fogleman but I seen your iterator more advanced.

**Comment by IteratorAdvance** [comment]
Hi, it's a good idea to have a golang port. I don't have much experience with golang but I guess C++ and be at least linked into golang and a wrapper in golang is possible.

**Comment by IteratorAdvance** [comment]
I'm closing this issue since currently the most urgent thing to do is a stable interface and documentations. You are welcome to re-open it after the first release though.
