### ISSUE TITLE
[macOS] some build errors

### ISSUE THREAD

**Issue by b-z** [IteratorAdvance/taichi#7]
I'm using Xcode building the project, but caught these errors:

##### 1. boost header including error:

> fatal error: 'boost/foreach.hpp' file not found

Fixed by adding the boost including path to "search paths".

##### 2. a link error:

> clang: error: no such file or directory: '/Users/Iterator/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib'

It seems that I should change "/Users/Iterator/homebrew" to my own path(in Build Settings--Other Linker Flags).
For me, it is "/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib"

**Comment by b-z** [comment]
The wiki has been updated (yesterday?)

**Comment by IteratorAdvance** [comment]
Hi Bowei,

The following lines of CMakeLists.txt was a hack, since usually OS X people have different version of python and it's tricky to set the correct one. Do you have any suggestions on how to improve this?

```
if (APPLE)
    set(PYTHON_INCLUDE_DIRS "/usr/include/python2.7/")
    set(PYTHON_LIBRARIES "/Users/Iterator/homebrew/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib")
endif ()
```

Thanks.

**Comment by IteratorAdvance** [comment]
And you are right that I updated the wiki, mainly to reduce the needed environment variables.

**Comment by IteratorAdvance** [comment]
I replaced the default python package finder in CMake with my customized one, which uses the current `python` interpreter by default.

```
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import sys; from distutils import sysconfig; sys.stdout.write(sysconfig.get_config_var('INCLUDEDIR') + '/python2.7/')"
            OUTPUT_VARIABLE PYTHON_INCLUDE_DIRS)
execute_process(COMMAND ${PYTHON_EXECUTABLE} -c "import sys; from distutils import sysconfig; sys.stdout.write(sysconfig.get_config_var('LIBDIR'))"
            OUTPUT_VARIABLE PYTHON_LIBRARY_DIR)
find_library(PYTHON_LIBRARY NAMES python2.7 PATHS ${PYTHON_LIBRARY_DIR} NO_DEFAULT_PATH NO_SYSTEM_ENVIRONMENT_PATH PATH_SUFFIXES x86_64-linux-gnu)

```
